# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 08:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceURL', '0003_auto_20171104_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='target_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes='https'), django.core.validators.RegexValidator(code='invalid', message='Enter a valid URL.', regex='^https://.*')]),
        ),
    ]
