# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 09:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AliceURL', '0007_auto_20171104_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='target_link',
            field=models.URLField(validators=[django.core.validators.RegexValidator(regex='^https://.*')]),
        ),
    ]
